services:
  redis:
    container_name: redis
    image: redis:7.0.8
    ports:
      - "6379:6379"
  app:
    build: 
      context: .
      target: dev
    ports:
      - "3000:3000"
    environment:
      - MONGO_DB_URL=${MONGO_DB_URL}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - PORT=${PORT}
    volumes:
      - .:/app
